version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./ai_core
      dockerfile: Dockerfile
    container_name: creative-muse-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - DATABASE_URL=sqlite:///./database/creative_muse.db
      - HF_TOKEN=${HF_TOKEN}
      - MASTER_KEY_PASSWORD=${MASTER_KEY_PASSWORD}
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
      - ./security:/app/security
    networks:
      - creative-muse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./creative-muse-react
      dockerfile: Dockerfile
    container_name: creative-muse-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - creative-muse-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: creative-muse-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./security/certificates:/etc/nginx/certs
    depends_on:
      - api
      - frontend
    networks:
      - creative-muse-network
    restart: unless-stopped

networks:
  creative-muse-network:
    driver: bridge

volumes:
  database_data:
  logs_data:
  security_data: