services:
  traefik:
    image: traefik:v3.0
    container_name: creative-muse-traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik-certificates:/letsencrypt
    networks:
      - creative-muse-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.creative-muse.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  creative-muse-ai:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - ENVIRONMENT=development
      - DEBUG=true
    expose:
      - "8000"
      - "8001"
      - "3000"
      - "5000"
      - "5173"
    networks:
      - creative-muse-network
    labels:
      - "traefik.enable=true"
      # Backend API (LLM)
      - "traefik.http.routers.backend.rule=Host(`api.creative-muse.local`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8001"
      # Frontend
      - "traefik.http.routers.frontend.rule=Host(`creative-muse.local`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      # Additional Services
      - "traefik.http.routers.services.rule=Host(`services.creative-muse.local`)"
      - "traefik.http.routers.services.entrypoints=web"
      - "traefik.http.routers.services.service=services"
      - "traefik.http.services.services.loadbalancer.server.port=5000"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: creative-muse-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - creative-muse-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mail.creative-muse.local`)"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "traefik.http.routers.mailhog.service=mailhog"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - mailhog-data:/maildir

networks:
  creative-muse-network:
    driver: bridge

volumes:
  python-cache:
  node-cache:
  traefik-certificates:
  mailhog-data: